### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by magicalyak**
This PR adds a dockerfile so you can run the following and see the app on Docker (replace magicalyak with your dockerhub name)
docker build --rm -t magicalyak/angular7-example-app .
docker run --rm -d -p 80:80/tcp magicalyak/angular7-example-app

### CODE REVIEW

**Comment by Ismaestro** [comment]
Thanks very much @magicalyak!

**Comment by magicalyak** [comment]
Thank you! I was looking for a good demo website and your creation is great! The container was fun to build. It uses one image to build everything and the final container is just the site (so it’s pretty lightweight) thanks again!!

**Comment by Ismaestro** [comment]
@all-contributors please add @magicalyak for docker

**Comment by Ismaestro** [comment]
https://github.com/all-contributors please add @magicalyak for infra

**Comment by Ismaestro** [comment]
@all-contributors please add @magicalyak for infra

**Pull request merged**
